name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    accept-flake-config = true

permissions:
  contents: read

jobs:
  check:
    runs-on: [self-hosted, nixos]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - run: nix flake check --print-build-logs
